[terminal]
osc52 = "CopyPaste"
shell = "/bin/zsh"
[env]
    TERM="xterm-256color"
[window]
opacity = 0.85
[font]
#normal = { family = "Iosevka Term medium"}
normal = { family = "IosevkaTerm NF Medium" }
# arch pkg: ttf-iosevkaterm-nerd
size = 10.0

[cursor]
style.shape = "Block"
style.blinking = "Never"
thickness = 0.3
unfocused_hollow = true

[mouse]
hide_when_typing = true



# Rose Pine
[colors.primary]
foreground = "#e3f1f2"
bright_foreground = "#fcfdfc"
dim_foreground = "#c1cdd8"
background = "#0e0d12"

[colors.cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.vi_mode_cursor]
text = "#e0def4"
cursor = "#524f67"

[colors.search.matches]
foreground = "#908caa"
background = "#26233a"

[colors.search.focused_match]
foreground = "#191724"
background = "#ebbcba"

[colors.hints.start]
foreground = "#908caa"
background = "#1f1d2e"

[colors.hints.end]
foreground = "#6e6a86"
background = "#1f1d2e"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#e0def4"
background = "#1f1d2e"

[colors.selection]
text = "#e0def4"
background = "#403d52"

[colors.normal]
black = "#22233d"
red = "#ba5454"
green = "#6dbc5c"
yellow = "#cdcc2f"
blue = "#5366b5"
magenta = "#b966d0"
cyan = "#73cdcb"
white = "#e3f1f2"

[colors.bright]
black = "#414c65"
red = "#d27575"
green = "#c3d678"
yellow = "#e9d248"
blue = "#7abfd5"
magenta = "#dd82c2"
cyan = "#91d3c4"
white = "#fcfdfc"

[colors.dim]
black = "#161323"
red = "#ac3e53"
green = "#3fa88b"
yellow = "#a3b42e"
blue = "#36ab8d"
magenta = "#8249bf"
cyan = "#56b1c6"
white = "#c1cdd8"
